### ISSUE TITLE
[META] Reports/Agendas - Ability to search attachment text

### ISSUE THREAD

**Issue by shrayshray** [datamade/la-metro-councilmatic#266]
Implementing system that allows users to search for board reports based on the
text in attachments. 
We are discussing internally and will provide response on whether this functionality should be the default search type, or whether it will be an optional addition to the standard search, e.g., use a "search attachments" checkbox next to the search bar.

**Comment by reginafcompton** [comment]
**Steps to add this search functionality**

(1) write a custom script that iterates over all attachments and converts Word, PDF, and Excel files into plain text. Run this script against the entire Metro database, and ultimately, integrate it into the regular data pipeline (i.e., run it every time we refresh data).

(2) configure and rebuild the search indexes to enable searching by attachment text - this entails creating a custom search template, ([as we did with NYC](https://github.com/datamade/nyc-council-councilmatic/blob/master/nyc/templates/search/indexes/nyc/bill_text.txt)), and possibly [adding/preparing a new field to the search index](https://github.com/datamade/la-metro-councilmatic/blob/master/lametro/search_indexes.py).

**Comment by reginafcompton** [comment]
**Questions to answer:**
- how much of a performance hit, after we add all the new text? 
- check or uncheck attachments: search for all (by default), just attachments, or do not search attachments? 

DataMade will have a first implementation of this issue by the end of April.

**Comment by hancush** [comment]
FYI – We'll need to push the completion of this issue to the May milestone.

**Comment by hancush** [comment]
**Road map:** 

1. We should add attachment text as a distinct field for search (to enable optional searching), to [the `BillIndex` search index](https://github.com/datamade/la-metro-councilmatic/blob/68f42bf1530c91ae9ce87cc3eccdbc5c69dff925/lametro/search_indexes.py#L10).
    - What's the best way to do this: Concatenate all attachment text and search via bill, or create parallel index for bill documents? (The "best" way will be informed by the answers to the next two questions.)
    - Is the purpose of searching attachment text, to surface the attachment, or the bill?
    - What is the default search functionality (bill text only, attachment text only, or bill text and attachment text)?
 
2. Then, most likely, we will need to extend / refactor [the `LAMetroCouncilmaticFacetedSearchView` view](https://github.com/datamade/la-metro-councilmatic/blob/68f42bf1530c91ae9ce87cc3eccdbc5c69dff925/lametro/views.py#L705) to alter the `SearchQueryset` to search different fields, depending on user input.

**Comment by hancush** [comment]
Re: our earlier questions,

1. I can see use cases for both of these alternatives, but the conversation which prompted this request on our side was about surfacing the report based on a related attachment.

2. Search everything (board reports + attachments), as default. With an option to deselect/uncheck a box and search just reports.

**Comment by shrayshray** [comment]
@hancush We've been testing this and have some feedback and questions:
1. How are search results ranked? It looks like they're ranked by date instead of relevancy ... we definitely do want them to rank by relevancy first.

2. Search for exact phrase using quotes isn't working. E.g., search for "Red Line" in screenshot below.
![searchwithquotes-staging](https://user-images.githubusercontent.com/28063988/41063622-029c82ac-698e-11e8-83c7-e09da1c48de6.PNG)

 3. When the search terms are found in the attachment, there is not preview text in the search results listing. Is it possible to display preview text from the attachment?
![missingtext-staging](https://user-images.githubusercontent.com/28063988/41063684-3083c0ea-698e-11e8-9a31-e886fb60c0bf.PNG)

4. Tags on a report don't work from search results where the search terms are found in the attachment. 
a. Tags on the search result:
![tagnoresults1-staging](https://user-images.githubusercontent.com/28063988/41064499-9a41d84e-6990-11e8-80aa-1405098e9874.PNG)

b. What happens after clicking the tag "Annual Program Evaluation (APE):
![tagnoresults2-staging](https://user-images.githubusercontent.com/28063988/41064555-b8dbf8f2-6990-11e8-962a-b6d8c29f917c.PNG)

c. Tags on results where the search term is found in the Report are somewhat inconsistent. In this case, the tag term "Strategic Plan":
![tagnoresults3-staging](https://user-images.githubusercontent.com/28063988/41064617-ed331e14-6990-11e8-8049-3dee091e7232.PNG)

d. Clicking the tag even retrieves results where the search term is in the attachment:
![tagnoresults4-staging](https://user-images.githubusercontent.com/28063988/41064677-233d1dca-6991-11e8-97fa-fb7887eb610a.PNG)

e. But in another case, the tag term "Board of Directors"
![tagnoresults5-staging](https://user-images.githubusercontent.com/28063988/41064795-7404d8f6-6991-11e8-9f4d-daa57cf13b9d.PNG)

f. retrieves all sorts of reports which are not tagged with "Board of Directors":
![tagnoresults6-staging](https://user-images.githubusercontent.com/28063988/41064834-8b842202-6991-11e8-8fa7-07fda1a2654e.PNG)

5. Is it possible for the search engine to ingest a synonym list? Metro's library has created several and they could be helpful here for connecting phrases, acronyms, etc., e.g., "Public-Private Partnership", "P3", "PPP".

Thanks for all your work on this, Hannah!

**Comment by hancush** [comment]
Hi, @shrayshray! Thank you for your detailed feedback! 

Re: point 1, search has always been ordered by date by default – would you mind opening a separate issue for that? Whatever default we use, I think we should also indicate it to the user, like this:

<img width="538" alt="screen shot 2018-06-06 at 4 51 42 pm" src="https://user-images.githubusercontent.com/12176173/41067107-f79e6746-69a9-11e8-919f-fa05a59db06f.png">

I've started working on your remaining feedback over in the `search_improvements` branch – I'll open up a PR to keep track of progress in the AM.

**Comment by reginafcompton** [comment]
Issues to complete:

- [ ] https://github.com/datamade/la-metro-councilmatic/issues/320
- [ ] https://github.com/datamade/la-metro-councilmatic/issues/321
- [ ] https://github.com/datamade/la-metro-councilmatic/issues/322
- [ ] https://github.com/datamade/la-metro-councilmatic/issues/323

**Comment by shrayshray** [comment]
@reginafcompton, thank you! I've been testing and will report back after Matt and Omar send feedback.

**Comment by shrayshray** [comment]
@reginafcompton Just got approval -- we're ready to deploy to production!

**Comment by reginafcompton** [comment]
@shrayshray - wonderful! I'll deploy this morning.

**Comment by reginafcompton** [comment]
We're live! Closing this issue via PR #325
